# SPDX-FileCopyrightText: Contributors to PyPSA-Eur <https://github.com/pypsa/pypsa-eur>
#
# SPDX-License-Identifier: CC0-1.0

version: 2

mkdocs:
  configuration: mkdocs.yml

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  apt_packages:
  - graphviz

python:
  install:
  - requirements: docs-at/requirements.txt
