[project]
channels = ["conda-forge", "bioconda", "fico-xpress"]
name = "pypsa-at"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.10"
pip = "*"
pycountry = "*"
pyam = ">=2.0"
"ruamel.yaml" = "*"
jpype1 = "*"
pypsa = ">=0.32.1"
atlite = ">=0.3"
linopy = ">=0.4.4"
powerplantmatching = ">=0.5.15,<0.7"
dask = "*"
xlrd = "*"
openpyxl = "*"
seaborn = "*"
snakemake-minimal = "<8.25"
memory_profiler = "*"
yaml = "*"
pytables = "*"
lxml = "*"
numpy = "*"
pandas = ">=2.1"
geopandas = ">=1"
xarray = ">=2023.11.0"
rioxarray = "*"
netcdf4 = "*"
networkx = "*"
scipy = "*"
glpk = "*"
shapely = ">=2.0"
pyscipopt = "*"
scip = "!=9.2.0"
matplotlib = "*"
proj = "*"
fiona = "*"
country_converter = "*"
geopy = "*"
tqdm = "*"
pytz = "*"
tabula-py = "*"
pyxlsb = "*"
graphviz = "*"
pre-commit = "*"
ipython = "*"
cartopy = "*"
descartes = "*"
rasterio = "==1.4.1"
libgdal-core = "<3.10.0"
pixi-pycharm = ">=0.0.8,<0.0.9"
marimo = ">=0.11.22,<0.12"
plotly = ">=6.0.1,<7"

[pypi-dependencies]
gurobipy = "*"
highspy = "*"
xpress = "*"
tsam = ">=2.3.1"
snakemake-storage-plugin-http = "*"
snakemake-executor-plugin-slurm = "*"
snakemake-executor-plugin-cluster-generic = "*"
