[project]
channels = ["conda-forge", "bioconda", "fico-xpress"]
name = "pypsa-at"
platforms = ["linux-64"]
version = "0.1.0"

[dependencies]
python = ">=3.10"
pip = "*"
pycountry = "*"
pyam = ">=2.0"
"ruamel.yaml" = "*"
jpype1 = "*"
pypsa = ">=0.33.2,<0.34"
atlite = ">=0.3"
linopy = ">=0.4.4"
powerplantmatching = ">=0.5.15,<0.7"
dask = "*"
xlrd = "*"
openpyxl = ">=3.1.5,<4"
seaborn = "*"
snakemake-minimal = "<8.25"
memory_profiler = "*"
yaml = "*"
pytables = "*"
lxml = "*"
numpy = "*"
pandas = ">=2.1"
geopandas = ">=1"
xarray = ">=2023.11.0"
rioxarray = "*"
netcdf4 = "*"
networkx = "*"
scipy = "*"
glpk = "*"
shapely = ">=2.0"
pyscipopt = "*"
scip = "!=9.2.0"
matplotlib = "*"
proj = "*"
fiona = "*"
country_converter = "*"
geopy = "*"
tqdm = "*"
pytz = "*"
tabula-py = "*"
pyxlsb = "*"
graphviz = "*"
pre-commit = "*"
ipython = "*"
cartopy = "*"
descartes = "*"
rasterio = "==1.4.1"
libgdal-core = "<3.10.0"

# additional dependencies for pypsa-at
pixi-pycharm="*"
marimo="*"
plotly="*"
pytest="*"
click="*"
folium="*"
xlsxwriter="*"
frozendict="*"
mkdocs="*"
mkdocs-material= {version = "*"}  # , extras = ["imaging"]
mkdocstrings-python="*"  # {version = "*"}  # , extras = ["python"]
mkdocs-material-extensions="*"
Pygments="*"
mkdocs-marimo="*"
mknotebooks="*"

#[environments]
#dev = {features = ["dev"], solve-group = "prod"}
#
#[feature.dev.dependencies]
#pixi-pycharm="*"
#marimo="*"
#plotly="*"
#pytest="*"
#click="*"
#folium="*"
#xlsxwriter="*"
#frozendict="*"
#mkdocs="*"
#mkdocs-material= {version = "*"}  # , extras = ["imaging"]
#mkdocstrings-python="*"  # {version = "*"}  # , extras = ["python"]
#mkdocs-material-extensions="*"
#Pygments="*"
#mkdocs-marimo="*"
#mknotebooks="*"

[pypi-dependencies]
gurobipy = "*"
highspy = "*"
xpress = "*"
tsam = ">=2.3.1"
snakemake-storage-plugin-http = "*"
snakemake-executor-plugin-slurm = "*"
snakemake-executor-plugin-cluster-generic = "*"
mkdocs-badges="*"
