[project]
authors = ["Philip Worschischek <philip.worschischek@aggm.at>"]
channels = ["conda-forge", "bioconda"]
name = "pypsa-de"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.10"
pip = "*"
pycountry = "*"
pyam = ">=2.0"
"ruamel.yaml" = "*"
jpype1 = "*"
pypsa = ">=0.32.1"
atlite = ">=0.3"
linopy = ">=0.4.4"
powerplantmatching = ">=0.5.15,<0.7"
dask = "*"
xlrd = "*"
openpyxl = "*"
seaborn = "*"
snakemake-minimal = ">=9"
memory_profiler = "*"
yaml = "*"
pytables = "*"
lxml = "*"
numpy = "*"
pandas = ">=2.1"
geopandas = ">=1"
xarray = ">=2024.3.0"
rioxarray = "*"
netcdf4 = "*"
libgdal-netcdf = "*"
networkx = "*"
scipy = "*"
glpk = "*"
shapely = ">=2.0"
matplotlib = "*"
proj = "*"
fiona = "*"
country_converter = "*"
geopy = "*"
tqdm = "*"
pytz = "*"
tabula-py = "*"
pyxlsb = "*"
graphviz = "*"
geojson = "*"
cartopy = "*"
descartes = "*"
rasterio = "*"
jupyter = "*"
ipython = "*"
pre-commit = "*"
ruff = "*"
pylint = "*"
pygments = ">=2.19.1,<3"
click = ">=8.1.8,<9"
folium = ">=0.19.5,<0.20"
frozendict = ">=2.4.6,<3"
markdown = ">=3.8,<4"
mkdocs = ">=1.6.1,<2"
mkdocs-marimo = ">=0.2.1,<0.3"
mkdocs-material = ">=9.6.12,<10"
mkdocs-material-extensions = ">=1.3.1,<2"
mkdocstrings-python = ">=1.16.10,<2"
mknotebooks = ">=0.8.0,<0.9"
pixi-pycharm = ">=0.0.8,<0.0.9"
plotly = ">=6.0.1,<7"
pymdown-extensions = ">=10.14.3,<11"
pytest = ">=8.3.5,<9"
xlsxwriter = ">=3.2.3,<4"

[pypi-dependencies]
gurobipy = "*"
highspy = "*"
pyscipopt = "*"
tsam = ">=2.3.6, <3"
entsoe-py = "*"
snakemake-storage-plugin-http = ">=0.3"
snakemake-executor-plugin-slurm = "*"
snakemake-executor-plugin-cluster-generic = "*"
xpress = ">=9.5.4, <10"
mkdocs-badges = ">=0.4.5, <0.5"
