[workspace]
authors = ["Philip Worschischek <philip.worschischek@aggm.at>"]
channels = ["conda-forge", "bioconda"]
name = "pypsa-at"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.10"
pip = "*"
pycountry = "*"
pyam = ">=2.0"
"ruamel.yaml" = "*"
jpype1 = "*"
pypsa = ">=0.32.1"
atlite = ">=0.3"
linopy = ">=0.4.4"
powerplantmatching = ">=0.5.15,<0.7"
dask = "*"
xlrd = "*"
openpyxl = "*"
seaborn = "*"
snakemake-minimal = ">=9"
snakemake-storage-plugin-http = ">=0.3"
snakemake-executor-plugin-slurm = "*"
snakemake-executor-plugin-cluster-generic = "*"
memory_profiler = "*"
yaml = "*"
pytables = "*"
lxml = "*"
numpy = "*"
pandas = ">=2.1"
geopandas = ">=1"
xarray = ">=2024.3.0,<2025.7.0"
rioxarray = "*"
netcdf4 = "*"
libgdal-netcdf = "*"
networkx = "*"
scipy = "*"
glpk = "*"
shapely = ">=2.0"
matplotlib = "*"
proj = "*"
fiona = "*"
country_converter = "*"
geopy = "*"
tqdm = "*"
pytz = "*"
tabula-py = "*"
pyxlsb = "*"
graphviz = "*"
geojson = "*"
pyscipopt = "*"
cartopy = "*"
descartes = "*"
rasterio = "*"
jupyter = "*"
ipython = "*"
pre-commit = "*"
ruff = "*"
pylint = "*"
ixmp4 = "<0.10.0"
pygments = ">=2.19.2,<3"
click = ">=8.2.1,<9"
folium = ">=0.20.0,<0.21"
frozendict = ">=2.4.6,<3"
markdown = ">=3.8.2,<4"
mkdocs = ">=1.6.1,<2"
mkdocs-marimo = ">=0.2.1,<0.3"
mkdocs-material = ">=9.6.16,<10"
mkdocs-material-extensions = ">=1.3.1,<2"
mkdocstrings-python = ">=1.16.12,<2"
mknotebooks = ">=0.8.0,<0.9"
pixi-pycharm = ">=0.0.8,<0.0.9"
ruff-lsp = ">=0.0.62,<0.0.63"
plotly = ">=6.2.0,<7"
pymdown-extensions = ">=10.16.1,<11"
pytest = ">=8.4.1,<9"
pytest-html = ">=4.1.1,<5"
pytest-cov = ">=6.2.1,<7"
pytest-xdist = ">=3.8.0,<4"
pytest-metadata = ">3"
xlsxwriter = ">=3.2.5,<4"
git-delta = ">=0.18.2,<0.19"
gitpython = ">=3.1.45,<4"
pandas-stubs = ">=2.3.0.250703,<3"

[pypi-dependencies]
gurobipy = "*"
highspy = "*"
tsam = ">=2.3.9, <3"
entsoe-py = "*"
xpress = ">=9.6.0, <10"
mkdocs-badges = ">=0.4.5, <0.5"
sourcery = ">=1.37.0, <2"
