[global]
subdirectory = "OS/tests"

[view.capacity.heat_capacity]

file_name  = "heat_capacity_{location}"

export_plotly = true
export_excel = false
export_CSV = false

[view.capacity.heat_capacity.mapping]
