# -*- coding: utf-8 -*-
# SPDX-FileCopyrightText: : 2017-2023 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: MIT
ExPol:
# UBA CO2 pathway instead of KSG targets
# Europen CO2 pathway fixed at 2030 for 2035-2050
# Kernnetz is not assumed to be built
# Not forcing renewables after 2030

  iiasa_database:
    reference_scenario: ExPol

  co2_budget_DE_source: UBA

  co2_budget:
    2020: 0.720 # average emissions of 2019 to 2021 relative to 1990, excl LULUCF, EEA data, European Environment Agency. (2023a). Annual European Union greenhouse gas inventory 1990–2021 and inventory report 2023 - CRF Table. https://unfccc.int/documents/627830
    2025: 0.675 # With existing measures (WEM) projection, CO2 excl LULUCF, European Environment Agency. (2023e). Member States’ greenhouse gas (GHG) emission projections 2023. https://www.eea.europa.eu/en/datahub/datahubitem-view/4b8d94a4-aed7-4e67-a54c-0623a50f48e8
    2030: 0.569
    2035: 0.502
    2040: 0.452
    2045: 0.431
    2050: 0.419

  costs:
    transmission: "underground" # either overhead line ("overhead") or underground cable ("underground")
  solving:
    constraints:
      limits_capacity_min:
        Generator:
          onwind:
            DE:
              2030: 86.5   # 75 % Wind-an-Land Law
          offwind:
            DE:
              2030: 17.3
              2035: 29.3
          solar:
            DE:
              2030: 161.25   # 75 % PV strategy
      # boundary condition of maximum volumes
      limits_capacity_max:
        Generator:
          offwind:
            DE:
              2020: 7.8
              2025: 11.3
              2030: 17.3 # 12 less than NEP, because of 1 year delay
              2035: 40 # 29.3 + half of extra projects
          onwind:
            DE:
              2030: 94.5 # uba Projektionsbericht
          solar:
            DE:
              2030: 215 # uba Projektionsbericht


  sector:
    district_heating:
      potential: 0.1

  offshore_nep_force:
    cutin_year: 2025
    cutout_year: 2035 # Hackily reduced to 2030 if delay_years: 1
    delay_years: 1


KN2045_Mix:
# Default scenario, defined in pypsa.de.yaml
# Ausgewogener Mix an Technologien zur Dekarbonisierung der Sektoren
# Breites Energieträgerportfolio in der Endenergie (Strom, Wasserstoff, synthetische Kraftstoffe)
# Ausbau der erneuerbare Stromerzeugung erreicht politisch gesetzte Ziele
# Importe erneuerbar erzeugter Energien auf mittlerem Niveau
# dient als Referenzszenario in der Familie der Ariadne-Szenarien


KN2045_Elek:
# Fokus auf dem Hochlauf von Technologien zur direkten Elektrifizierung der Sektoren
# Strom als präferierter Energieträger in der Endenergie, andere Energieträger ergänzend, wo nötig (Wasserstoff, synthetische Kraftstoffe)
# Ausbau der erneuerbaren Stromerzeugung erreicht politisch gesetzte Ziele
# Importe erneuerbar erzeugter Energien auf mittlerem Niveau

  iiasa_database:
    reference_scenario: KN2045_Elek

  solving:
    constraints:
      limits_volume_max:
        # constrain electricity import in TWh
        electricity_import:
          DE:
            2020: -20
            2025: 0
            2030: 0
            2035: 50
            2040: 100
            2045: 150
            2050: 150
        electrolysis:
          DE:
            2020: 0
            2025: 5
            2030: 45
            2035: 95
            2040: 145
            2045: 200
            2050: 200
        h2_derivate_import:
          DE:
            2020: 0
            2025: 0
            2030: 10
            2035: 70
            2040: 130
            2045: 200
            2050: 200
        h2_import:
          DE:
            2020: 0
            2025: 5
            2030: 10
            2035: 90
            2040: 170
            2045: 250
            2050: 250

  industry:
    steam_biomass_fraction: 0.4
    steam_hydrogen_fraction: 0.1
    steam_electricity_fraction: 0.5

KN2045_H2:
# Fokus stärker auf dem Hochlauf von Technologien zur indirekten Elektrifizierung der Sektoren
# Verstärkter Einsatz von Wasserstoff und synthetischen Kraftstoffen - erneuerbar erzeugt und auch importiert
# Direkte Elektrifizierung spielt dennoch wesentliche Rolle bei der Dekarbonisierung der Endenergie
# Ausbau der erneuerbaren Stromerzeugung erreicht politisch gesetzte Ziele

  iiasa_database:
    reference_scenario: KN2045_H2

  solving:
    constraints:
      limits_volume_max:
        # constrain electricity import in TWh
        electricity_import:
          DE:
            2020: -20
            2025: 0
            2030: 0
            2035: 30
            2040: 70
            2045: 100 # scenario guidelines
            2050: 100

        # constrain hydrogen import in TWh
        h2_import:
          DE:
            2020: 0
            2025: 5
            2030: 45 # scenario guidelines
            2035: 155
            2040: 265
            2045: 400 # scenario guidelines
            2050: 400
        # import of h2 derivatives in TWh
        h2_derivate_import:
          DE:
            2020: 0
            2025: 0
            2030: 10 # scenario guidelines
            2035: 140
            2040: 270
            2045: 400 # scenario guidelines
            2050: 400
        electrolysis:
          DE:
            2020: 0
            2025: 5
            2030: 45 # scenario guidelines
            2035: 160
            2040: 275
            2045: 400 # scenario guidelines
            2050: 400

      limits_volume_min:
        electrolysis:
          DE:
            2025: 0
            2030: 0
            2035: 0
            2040: 0
            2045: 200
            2050: 200

  industry:
    steam_biomass_fraction: 0.4
    steam_hydrogen_fraction: 0.5
    steam_electricity_fraction: 0.1

KN2045_NFniedrig:
# Ausgewogener Mix an Technologien zur Dekarbonisierung der Sektoren
# Breites Energieträgerportfolio in der Endenergie (Strom, Wasserstoff, synthetische Kraftstoffe)
# Ausbau der erneuerbare Stromerzeugung erreicht politisch gesetzte Ziele
# Importe erneuerbar erzeugter Energien auf mittlerem Niveau
# dient als Referenzszenario in der Familie der Ariadne-Szenarien

  iiasa_database:
    reference_scenario: KN2045_NFniedrig

  sector:
    reduce_space_heat_exogenously_factor:
      2020: 0.0
      2025: 0.08
      2030: 0.16
      2035: 0.25
      2040: 0.34
      2045: 0.43
      2050: 0.50

KN2045_NFhoch:
# Ausgewogener Mix an Technologien zur Dekarbonisierung der Sektoren
# Breites Energieträgerportfolio in der Endenergie (Strom, Wasserstoff, synthetische Kraftstoffe)
# Ausbau der erneuerbare Stromerzeugung erreicht politisch gesetzte Ziele
# Importe erneuerbar erzeugter Energien auf mittlerem Niveau
# dient als Referenzszenario in der Familie der Ariadne-Szenarien

  iiasa_database:
    reference_scenario: KN2045_NFhoch

  sector:
    reduce_space_heat_exogenously_factor:
      2020: 0.0
      2025: 0.06
      2030: 0.12
      2035: 0.18
      2040: 0.24
      2045: 0.29
      2050: 0.33

AT10_KN2040:
# Basisszenario für PyPSA-AT mit Anpassungen des KN2045_Mix Szenarios aus PyPSA-DE with
#   * custom administrative clustering für Austrian regions
#   * calibrations
  run:
    prefix: v2025.03   # PyPSA-AT scenario names

  # restore pypsa-eur defaults
  countries: ['AL', 'AT', 'BA', 'BE', 'BG', 'CH', 'CZ', 'DE', 'DK', 'EE', 'ES', 'FI', 'FR', 'GB', 'GR', 'HR', 'HU', 'IE', 'IT', 'LT', 'LU', 'LV', 'ME', 'MK', 'NL', 'NO', 'PL', 'PT', 'RO', 'RS', 'SE', 'SI', 'SK', 'XK']
  snapshots:
    start: "2013-01-01"
    end: "2014-01-01"
    inclusive: 'left'
  atlite:
    cutout_directory: cutouts
    default_cutout: europe-2013-sarah3-era5
    nprocesses: 4
    show_progress: false
    cutouts:
      # use 'base' to determine geographical bounds and time span from config
      # base:
      # module: era5
      europe-2013-sarah3-era5:
        module: [sarah, era5] # in priority order
        x: [-12., 42.]
        y: [33., 72.]
        dx: 0.3
        dy: 0.3
        time: ['2013', '2013']
  renewable:
    onwind:
      cutout: default
    offwind-ac:
      cutout: default
    offwind-dc:
      cutout: default
    offwind-float:
      cutout: default
    solar:
      cutout: default
    solar-hsat:
      cutout: default
    hydro:
      cutout: default
  lines:
    dynamic_line_rating:
      cutout: default

  clustering:
    mode: administrative
    administrative:
      level: 0 # countries
      AT: 2 # 10 regions
      DE: 1 # 16 regions
      DK: 1 # +1 islands
      GB: 1 # +1 North Ireland
      FR: 1 # +1 islands
      IT: 1 # +2 islands
      ES: 1 # +1 islands
    temporal:
      resolution_sector: 365H

  sector:
    v2g: true
    solar_thermal: true
    biomass_transport: true
    regional_methanol_demand: true
    gas_network: true
    electrobiofuels: true
    biosng: true
    biosng_cc: true
    bioH2: true
    municipal_solid_waste: true
    cluster_heat_buses: true
    hydrogen_turbines: true
    methanol:
      regional_methanol_demand: true
      methanol_reforming: true
      methanol_reforming_cc: true
      methanol_to_kerosene: true
      methanol_to_power:
        ccgt: true
        ccgt_cc: true
        ocgt: true
        allam: true
      biomass_to_methanol: true
      biomass_to_methanol_cc: true
    ammonia: true
    regional_co2_sequestration_potential:
      enable: true
      attribute:
      - conservative estimate Mt
      - conservative estimate GAS Mt
      - conservative estimate OIL Mt
      - conservative estimate aquifer Mt
      include_onshore: false
      min_size: 3
      max_size: 25
      years_of_storage: 25
    co2_network: true
    imports:  # this is for renewable gas/H2/methanol/oil imports
      enable: true
    # gas compression seems incompatible with gas network. Pipelines connect
    # gas buses, however Generators in '{node} gas primary' buses introduce gas
    # energy at local nodes, which is then compressed to the local gas bus.
    # As a result, gas is not transported via pipelines.
    # Note, that gas compression AC withdrawal still is implemented. Losses are
    # for methane to atmosphere.
    gas_compression_losses: 0  # 0.04
    # oil_refining_emissions: 0  # 0.013

  solving:
    constraints:
      limits_capacity_min:
        electrolysis:
          AT:
            # EAG Ausbauziel: 1 GW Elektrolyseleistung in Ö.
            2030: 1.0
            2040: 1.0
            2050: 1.0
    solver:
      name: highs
      options: highs-default

  solver_options:
    # https://ergo-code.github.io/HiGHS/dev/options/definitions/
    highs-default:
      threads: 0

  mods:
    modify_nuts3_shapes: true
    modify_austrian_transmission_capacities: true  # scale_capacity does not work for Line components
    modify_population_layouts: true
