# -*- coding: utf-8 -*-
# SPDX-FileCopyrightText: : 2017-2023 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: MIT

KN2040_AT35DE5:
  description: Basisszenario für PyPSA-AT mit hoher zeitlicher und räumlicher Auflösung
  clustering:
    mode: administrative
    administrative:
      AT: 3 # 10 regions if NUTS 2, 35 if NUTS 3
      DE: 3 # NUTS3 as a proxy for 5 regions
    temporal:
      resolution_sector: 3H
  solving:
    solver:
      name: gurobi
      options: gurobi-default
  mods:
    modify_nuts3_shapes: AT35DE5

KN2040_AT35DE5_testrun:
  description: Basisszenario für PyPSA-AT mit geringer zeitlicher und hoher räumlicher Auflösung
  clustering:
    mode: administrative
    administrative:
      AT: 3 # 10 regions if NUTS 2, 35 if NUTS 3
      DE: 3 # NUTS3 as a proxy for 5 regions
    temporal:
      resolution_sector: 120H
  solving:
    solver:
      name: highs
      options: highs-default
  mods:
    modify_nuts3_shapes: AT35DE5

KN2040_AT10DE5_testrun:
  description: Basisszenario für PyPSA-AT mit geringer Auflösung
  clustering:
    mode: administrative
    administrative:
      AT: 2 # 10 regions if NUTS 2, 35 if NUTS 3
      DE: 3 # NUTS3 as a proxy for 5 regions
    temporal:
      resolution_sector: 120H
  solving:
    solver:
      name: highs
      options: highs-default
  mods:
    modify_nuts3_shapes: AT10DE5
