[global]

[view.capacity.heat]
name = "District Heat Production Capacities"
unit = "GW"
file_name = "capacity_heat_{location}"
cutoff = 0.0001
legend_order = [
    "Storage Out",
    "Solar Thermal",
    "Fischer-Tropsch",
    "Biomass CHP",
    "Oil CHP",
    "Waste CHP",
    "Electrolysis",
    "Haber-Bosch",
    "Direct Air Capture",
    "CHP",
    "Heat Vent",
    "Methanolisation",
    "Fuel Cell",
    "Resistive Heater",
    "Gas Boiler",
    "Gas CHP",
    "Coal CHP",
    "Heat Pump",
    "Storage In",
]
checks = []
exports = ["csv", "excel"]

[view.capacity.heat.categories]
"DAC" = "Direct Air Capture"
"Fischer-Tropsch" = "Fischer-Tropsch"
"Haber-Bosch" = "Haber-Bosch"
"H2 Electrolysis" = "Electrolysis"
"H2 Fuel Cell" = "Fuel Cell"
"methanolisation" = "Methanolisation"
"urban central air heat pump" = "Heat Pump"
"urban central CHP" = "CHP"
"urban central coal CHP" = "Coal CHP"
"urban central gas CHP" = "Gas CHP"
"urban central oil CHP" = "Oil CHP"
"waste CHP" = "Waste CHP"
"waste CHP CC" = "Waste CHP"
"urban central gas boiler" = "Gas Boiler"
"urban central heat vent" = "Heat Vent"
"urban central lignite CHP" = "Coal CHP"
"urban central resistive heater" = "Resistive Heater"
"urban central solar thermal" = "Solar Thermal"
"urban central solid biomass CHP" = "Biomass CHP"
"urban central water tanks charger" = "Storage In"
"urban central water tanks discharger" = "Storage Out"

[view.capacity.ac_production]
name = "Optimal Capacity Electricity"
unit = "GW"
file_name = "capacity_ac_production_{location}"
cutoff = 0.0001
legend_order = [
    "Nuclear Power",
    "Thermal Powerplants",
    "Pumped Hydro Storage",
    "Reservoir",
    "Run-of-River",
    "Wind Power",
    "Coal",
    "Hydrogen",
    "Solar Power",
    "Solid Biomass",
    "Biogas",
    "Oil",
]
checks = []
exports = ["csv"]

[view.capacity.ac_production.categories]
"CCGT" = "Thermal Powerplants"
"H2 OCGT" = "Hydrogen"
"H2 turbine" = "Hydrogen"
"OCGT" = "Thermal Powerplants"
"PHS" = "Pumped Hydro Storage"
"allam gas" = "Thermal Powerplants"
"biogas" = "Biogas"
"coal" = "Coal"
"hydro" = "Reservoir"
"lignite" = "Coal"
"nuclear" = "Nuclear Power"
"offwind-ac" = "Wind Power"
"offwind-dc" = "Wind Power"
"oil" = "Oil"
"onwind" = "Wind Power"
"ror" = "Run-of-River"
"solar" = "Solar Power"
"solar-hsat" = "Solar Power"
"solid biomass" = "Solid Biomass"
"urban central CHP" = "Thermal Powerplants"
"urban central coal CHP" = "Thermal Powerplants"
"urban central gas CHP" = "Thermal Powerplants"
"urban central lignite CHP" = "Thermal Powerplants"
"urban central oil CHP" = "Thermal Powerplants"
"urban central solid biomass CHP" = "Thermal Powerplants"
"waste CHP" = "Thermal Powerplants"
"waste CHP CC" = "Thermal Powerplants"

[view.balance.hydrogen]
name = "Hydrogen Energy Balance"
unit = "TWh"
file_name = "nodal_balance_hydrogen_{location}"
cutoff = 0.001
legend_order = [
    # production ordered from zero to outside
    "Electrolysis",
    "SMR",
    "H2 from Solid Biomass",
    "Ammonia Cracking",
    "Storage",
    "Import Domestic",
    "Import European",
    # demand ordered from zero to outside:
    "Methanolisation",
    "Industry",
    "Transport",
    "Electricity",
    "Haber-Bosch",
    "Fischer-Tropsch",
    "Sabatier",
    "Synth. Fuels",
    "Export Domestic",
    "Export European",
]
checks = ["balances_almost_zero"]
exports = ["csv", "excel"]

[view.balance.hydrogen.categories]
"ammonia cracker" = "Ammonia Cracking"
"Export European" = "Export European"
"Export Domestic" = "Export Domestic"
"Fischer-Tropsch" = "Fischer-Tropsch"
"H2 Electrolysis" = "Electrolysis"
"H2 Fuel Cell" = "Electricity"
"H2 OCGT" = "Electricity"
"H2 for industry" = "Industry"
"H2 turbine" = "Electricity"
"H2 Store" = "Storage"
"Haber-Bosch" = "Haber-Bosch"
"Import European" = "Import European"
"Import Domestic" = "Import Domestic"
"SMR" = "SMR"
"SMR CC" = "SMR"
"Sabatier" = "Sabatier"
"electrobiofuels" = "Synth. Fuels"
"land transport fuel cell" = "Transport"
"methanolisation" = "Methanolisation"
"solid biomass to hydrogen" = "H2 from Solid Biomass"

[view.balance.electricity]
name = "Electricity Energy Balance"
unit = "TWh"
file_name = "nodal_balance_electricity_{location}"
cutoff = 0.01  # TWh
legend_order = [
    # production ordered from zero to outside
    "Hydro Power",
    "Nuclear Power",
    "Wind Power",
    "Distribution Grid",  # demand and production!
    "Solar Power",
    "Solid Biomass",
    "Waste",
    "Coal",
    "Methane",
    "Hydrogen",
    "Oil",
    "Import Domestic",
    "Import Foreign",

    # demand ordered from zero to outside

    "Base Load",
    "Agriculture",
    "Industry",
    "Transport",
    "Hydrogen",
    "Heat",
    "Hydrogen Compression",
    "Methane Compression",
    "Methanolisation",
    "Haber-Bosch",
    "Electrolysis",
    "Direct Air Capture",
    "Pumped Hydro Storage",
    "Export Domestic",
    "Export Foreign"

]
checks = ["balances_almost_zero"]
exports = []  # "csv", "excel"

[view.balance.electricity.categories]
"BEV charger" = "Transport"
"CCGT" = "Methane"
"DAC" = "Direct Air Capture"
"Export Domestic" = "Export Domestic"
"Export Foreign" = "Export Foreign"
"H2 Electrolysis" = "Electrolysis"
"H2 OCGT" = "Hydrogen"
"H2 pipeline" = "Hydrogen Compression"
"H2 pipeline (Kernnetz)" = "Hydrogen Compression"
"Haber-Bosch" = "Haber-Bosch"
"Import Domestic" = "Import Domestic"
"Import Foreign" = "Import Foreign"
"OCGT" = "Methane"
"PHS" = "Pumped Hydro Storage"
"V2G" = "Transport"
"agriculture electricity" = "Agriculture"
"coal" = "Coal"
"electricity" = "Base Load"
"electricity distribution grid" = "Distribution Grid"
"gas pipeline" = "Methane Compression"
"hydro" = "Hydro Power"
"industry electricity" = "Industry"
"lignite" = "Coal"
"methanolisation" = "Methanolisation"
"nuclear" = "Nuclear Power"
"offwind-ac" = "Wind Power"
"offwind-dc" = "Wind Power"
"onwind" = "Wind Power"
"ror" = "Hydro Power"
"rural air heat pump" = "Heat"
"rural ground heat pump" = "Heat"
"rural resistive heater" = "Heat"
"solar" = "Solar Power"
"solar rooftop" = "Solar Power"
"solar-hsat" = "Solar Power"
"solid biomass" = "Solid Biomass"
"urban central CHP" = "Methane"
"urban central air heat pump" = "Heat"
"urban central coal CHP" = "Coal"
"urban central gas CHP" = "Methane"
"urban central lignite CHP" = "Coal"
"urban central oil CHP" = "Oil"
"urban central resistive heater" = "Heat"
"urban central solid biomass CHP" = "Solid Biomass"
"urban decentral air heat pump" = "Heat"
"urban decentral resistive heater" = "Heat"
"waste CHP" = "Waste"
"waste CHP CC" = "Waste"


[view.balance.heat]
name = "Heat Energy Balance"
unit = "TWh"
file_name = "nodal_balance_heat_{location}"
cutoff = 0.001
legend_order = [
    # production ordered from zero to outside
    "Electricity",
    "Electricity (low voltage)",
    "Oil",
    "Solar Power",
    "Methane",
    "Hydrogen",
    "Electrolysis",
    "Sabatier",
    "Methanolisation",
#    "CHP",
    "Waste",
    "CO2",
    "Coal",
    "Fischer-Tropsch",
    "Haber-Bosch",
    "Biomass",
    "Solid Biomass",
    # demand ordered from zero to outside
    "Demand",
    "Agriculture",
    "Direct Air Capture",
    "Industry",
    "Distribution Losses",
    "Heat Ventilation"
]
checks = ["balances_almost_zero"]
exports = []  # "csv", "excel"

[view.balance.heat.categories]
#"AC" = "Electricity"
#"H2" = "Hydrogen"
#"co2 stored" = "CO2"
#"coal" = "Coal"
#"gas" = "Methane"
#"lignite" = "Coal"
#"low voltage" = "Electricity (low voltage)"
#"non-sequestered HVC" = "Waste"
#"oil" = "Oil"
#"solid biomass" = "Solid Biomass"
#
#"DAC" = "Direct Air Capture"
#"Fischer-Tropsch" = "Fischer-Tropsch"
#"H2 Electrolysis" = "Electrolysis"
#"Haber-Bosch" = "Haber-Bosch"
#"Sabatier" = "Sabatier"
#"agriculture heat" = "Agriculture"
#"low-temperature heat for industry" = "Industry"
#"methanolisation" = "Methanolisation"
#"rural air heat pump" = "Electricity"
#"rural biomass boiler" = "Biomass"
#"rural gas boiler" = "Methane"
#"rural ground heat pump" = "Electricity"
#"rural heat" = "Demand"
#"rural heat vent" = "Heat Ventilation"
#"rural oil boiler" = "Oil"
#"rural resistive heater" = "Electricity"
#"rural solar thermal" = "Solar Power"
#"urban central CHP" = "Methane"  # connected to gas bus
#"urban central air heat pump" = "Electricity"
#"urban central coal CHP" = "Coal"
#"urban central gas CHP" = "Methane"
#"urban central gas boiler" = "Methane"
#"urban central heat" = "Demand"
#"urban central heat losses" = "Distribution Losses"
#"urban central heat vent" = "Heat Ventilation"
#"urban central lignite CHP" = "Coal"
#"urban central oil CHP" = "Oil"
#"urban central resistive heater" = "Electricity"
#"urban central solid biomass CHP" = "Biomass"
#"urban central water tanks" = "Storage"
##"urban central water tanks charger" = ""
##"urban central water tanks discharger" = ""
#"urban decentral air heat pump" = "Electricity"
#"urban decentral biomass boiler" = "Biomass"
#"urban decentral gas boiler" = "Methane"
#"urban decentral heat" = "Demand"
#"urban decentral heat vent" = "Heat Ventilation"
#"urban decentral oil boiler" = "Oil"
#"urban decentral resistive heater" = "Electricity"
#"urban decentral solar thermal" = "Solar Power"
#"waste CHP" = "Waste"
#"waste CHP CC" = "Waste"


[view.demand.heat_production]
name = "Energy Demand for Heat Production"
unit = "TWh"
file_name = "nodal_demand_heat_production_{location}"
cutoff = 0.001
legend_order = [
    # from zero upwards:
    "Oil",
    "Coal",
    "Methane",
    "Waste",
    "Solid Biomass",
    "Electricity",
    "Solar Power",
    "Hydrogen"
]
checks = []
exports = ["excel"]

[view.demand.heat_production.categories]
"AC" = "Electricity"
"H2" = "Hydrogen"
"coal" = "Coal"
"gas" = "Methane"
"renewable gas" = "Methane"
"lignite" = "Coal"
"low voltage" = "Electricity"
"non-sequestered HVC" = "Waste"
"oil" = "Oil"
"rural heat" = "Solar Power"
"solid biomass" = "Solid Biomass"
"urban central heat" = "Solar Power"
"urban decentral heat" = "Solar Power"

[view.fed.total]
name = "Final Energy Demand"
unit = "TWh"
file_name = "nodal_fed_total_{location}"
cutoff = 0.001
legend_order = [
    # from zero upwards:
    ""
]
checks = []
exports = ["excel"]

[view.fed.total.categories]
"" = ""

[view.timeseries.hydrogen]
name = "Hydrogen Production and Demand"
unit = "MWh"
file_name = "timeseries_hydrogen_{location}_{year}"
cutoff = 0.001
legend_order = [
    "Net Import",
    "Sabatier",
    "Storage Out",
    "H2 from Solid Biomass",
    "Electrolysis",
    # --- zero ---
    "Storage In",
    "Net Export",
    "Electricity",
    "Haber-Bosch",
    "Synth. Fuels",
    "Ammonia Cracking",
    "Methanolisation",
    "SMR",
    "Fischer-Tropsch",
    "Transport",
    "Industry",
]
checks = ["balances_almost_zero"]
exports = []

[view.timeseries.hydrogen.categories]
"ammonia cracker" = "Ammonia Cracking"
"Fischer-Tropsch" = "Fischer-Tropsch"
"H2 Electrolysis" = "Electrolysis"
"H2 Fuel Cell" = "Electricity"
"H2 OCGT" = "Electricity"
"H2 for industry" = "Industry"
"H2 turbine" = "Electricity"
"Haber-Bosch" = "Haber-Bosch"
"SMR" = "SMR"
"SMR CC" = "SMR"
"Sabatier" = "Sabatier"
"electrobiofuels" = "Synth. Fuels"
"land transport fuel cell" = "Transport"
"methanolisation" = "Methanolisation"
"solid biomass to hydrogen" = "H2 from Solid Biomass"
"Net Export" = "Net Export"
"Net Import" = "Net Import"
"Storage In" = "Storage In"
"Storage Out" = "Storage Out"

[view.capacity.ac_storage]
name = "Power Storage Volumes"
unit = "TWh"
file_name = "capacity_ac_storage_{location}"
cutoff = 0.00001  # 1 MWh
legend_order = []
checks = []
exports = []

[view.capacity.ac_storage.categories]
"" = ""

[view.capacity.gas_storage]
name = "Gas Storage Volumes"
unit = "TWh"
file_name = "capacity_gas_storage_{location}"
cutoff = 0.00001  # 1 MWh
legend_order = ["Methane Store", "Hydrogen Store"]
checks = ["balances_almost_zero"]
exports = []

[view.capacity.gas_storage.categories]
"H2 Store" = "Hydrogen Store"
"gas" = "Methane Store"

[view.transmissions.transmission]
name = "Transmission_test"
unit = "TWh"
file_name = "grid_test_{location}"
cutoff = 0.00001  # 1 MWh
legend_order = []
checks = []
exports = []

[view.transmissions.transmission.categories]
"" = ""
