[global]

[view.capacity.heat]
name = "District Heat Production Capacities"
unit = "GW"
file_name = "capacity_heat_{location}"
cutoff = 0.0001
legend_order = [
    "Storage Out",
    "Solar Thermal",
    "Fischer-Tropsch",
    "Biomass CHP",
    "Oil CHP",
    "Waste CHP",
    "Electrolysis",
    "Haber-Bosch",
    "Direct Air Capture",
    "CHP",
    "Heat Vent",
    "Methanolisation",
    "Fuel Cell",
    "Resistive Heater",
    "Gas Boiler",
    "Gas CHP",
    "Coal CHP",
    "Heat Pump",
    "Storage In",
]

[view.capacity.heat.checks]
balances_almost_zero = false

[view.capacity.heat.export]
plotly = true
csv = true
excel = true

[view.capacity.heat.categories]
"DAC" = "Direct Air Capture"
"Fischer-Tropsch" = "Fischer-Tropsch"
"Haber-Bosch" = "Haber-Bosch"
"H2 Electrolysis" = "Electrolysis"
"H2 Fuel Cell" = "Fuel Cell"
"methanolisation" = "Methanolisation"
"urban central air heat pump" = "Heat Pump"
"urban central CHP" = "CHP"
"urban central coal CHP" = "Coal CHP"
"urban central gas CHP" = "Gas CHP"
"urban central oil CHP" = "Oil CHP"
"waste CHP" = "Waste CHP"
"waste CHP CC" = "Waste CHP"
"urban central gas boiler" = "Gas Boiler"
"urban central heat vent" = "Heat Vent"
"urban central lignite CHP" = "Coal CHP"
"urban central resistive heater" = "Resistive Heater"
"urban central solar thermal" = "Solar Thermal"
"urban central solid biomass CHP" = "Biomass CHP"
"urban central water tanks charger" = "Storage In"
"urban central water tanks discharger" = "Storage Out"


[view.capacity.electricity_capacity]

name = "Optimal Capacity Electricity"
unit = "GW"
file_name  = "electricity_capacities_{location}"
cutoff = 0.0
legend_order = [

    "Nuclear Power",
    "Thermal Powerplants",
    "Pumped Hydro Storage",
    "Reservoir",
    "Run-of-River",
    "Wind Power",

]

[view.capacity.electricity_capacity.export]
plotly = true
csv = true
excel = false

[view.capacity.electricity_capacity.checks]
all_categories_mapped = true
no_superfluous_categories = true
yearly_balances_almost_zero = false
legend_entry_order = true

[view.capacity.electricity_capacity.categories]

"DAC" = "Direct Air Capture"
"Run-of-River" = "Run-of-River"
"Reservoir" = "Reservoir"
"Pumped Hydro Storage" = "Pumped Hydro Storage"
"Thermal Powerplants" = "Thermal Powerplants"
"urban central coal CHP" = "Coal CHP"
"solar-hsat" = "Solar Power"
"waste CHP" = "Waste CHP"
"Biomass" = "Biomass"
"waste CHP CC" = "Waste CHP"
#hydrogen
#hydrogen Turbine
"CCGT" = "Gas CHP"
"urban central gas CHP" = "Gas CHP"
"urban central CHP" = "CHP"
"urban central CHP CC" = "CHP"
"solar" = "Solar Power"
"onwind" = "Wind Power"
"allam gas" = "Gas CHP"
"Battery Storage" = "Battery Storage Output"

"H2 Fuel Cell" = "Fuel Cell (electricity)"
"methanolisation" = "Methanolisation (Heat)"
"urban central air heat pump" = "Heat Pump"
"H2 Electrolysis" = "Electrolysis (Heat)" #ToDO: why is H2 Electrolysis in this Index?

#"urban central gas CHP" = "Gas CHP"
"urban central oil CHP" = "Oil CHP"
'H2 OCGT' =  "OCGT Electricity"
'H2 pipeline' = 'H2 pipeline'
'H2 pipeline (Kernnetz)' = 'H2 pipeline (Kernnetz)'
'H2 turbine' =  "Accumulated Turbining"
"Haber-Bosch" = "Haber-Bosch (Heat)" #ToDO: why is Haber Bosch in this Index?
"OCGT" =  "OCGT Electricity"
"PHS" = "PHS Out" #ToDO: Is out correct?
"battery charger" = "Storage In" #ToDO: Is "in" right?
'battery discharger' = "Storage Out"
"biogas" = "Biogas"
"coal" = "Coal"
"electricity distribution grid" = "Electricity Distribution Grid"
"gas pipeline" = "Gas Pipeline"
"hydro" = "Storage Out"
"lignite" = "Lignite"
"nuclear" = "Nuclear Power"
"offwind-ac" = "Offwind"
"offwind-dc" = "Offwind"
"oil" = "Oil"
"ror" = "Run of River"
"urban central gas boiler" = "Gas Boiler"
"urban central heat vent" = "Heat Vent"
"urban central lignite CHP" = "Coal CHP"
"urban central resistive heater" = "Resistive Heater"
"urban central solar thermal" = "Solar Thermal"
"urban central solid biomass CHP" = "Biomass CHP"
"urban central solid biomass CHP CC" = "Biomass CHP"
"urban central water tanks charger" = "Storage In"
"urban central water tanks discharger" = "Storage Out"
"solid biomass" = "Solid Biomass"

[view.balance.hydrogen]
name = "Hydrogen Energy Balance"
unit = "TWh"
file_name = "nodal_balance_hydrogen_{location}"
cutoff = 0.001
legend_order = [
    # production ordered from zero to outside
    "Electrolysis",
    "SMR",
    "H2 from Solid Biomass",
    "Ammonia Cracking",
    "Storage",
    "Import Domestic",
    "Import European",
    # demand ordered from zero to outside:
    "Methanolisation",
    "Industry",
    "Transport",
    "Electricity",
    "Haber-Bosch",
    "Fischer-Tropsch",
    "Sabatier",
    "Synth. Fuels",
    "Export Domestic",
    "Export European",
]

[view.balance.hydrogen.checks]
balances_almost_zero = true

[view.balance.hydrogen.export]
plotly = true
csv = true
excel = true

[view.balance.hydrogen.categories]
"ammonia cracker" = "Ammonia Cracking"
"Export European" = "Export European"
"Export Domestic" = "Export Domestic"
"Fischer-Tropsch" = "Fischer-Tropsch"
"H2 Electrolysis" = "Electrolysis"
"H2 Fuel Cell" = "Electricity"
"H2 OCGT" = "Electricity"
"H2 for industry" = "Industry"
"H2 turbine" = "Electricity"
"H2 Store" = "Storage"
"Haber-Bosch" = "Haber-Bosch"
"Import European" = "Import European"
"Import Domestic" = "Import Domestic"
"SMR" = "SMR"
"SMR CC" = "SMR"
"Sabatier" = "Sabatier"
"electrobiofuels" = "Synth. Fuels"
"land transport fuel cell" = "Transport"
"methanolisation" = "Methanolisation"
"solid biomass to hydrogen" = "H2 from Solid Biomass"

[view.timeseries.hydrogen]
name = "Hydrogen Production and Demand"
unit = "MWh"
file_name = "timeseries_hydrogen_{location}_{year}"
cutoff = 0.001
legend_order = [
    "Net Import",
    "Sabatier",
    "Storage Out",
    "H2 from Solid Biomass",
    "Electrolysis",
    # --- zero ---
    "Storage In",
    "Net Export",
    "Electricity",
    "Haber-Bosch",
    "Synth. Fuels",
    "Ammonia Cracking",
    "Methanolisation",
    "SMR",
    "Fischer-Tropsch",
    "Transport",
    "Industry",
]

[view.timeseries.hydrogen.checks]
balances_almost_zero = true

[view.timeseries.hydrogen.export]
plotly = true
csv = false
excel = false

[view.timeseries.hydrogen.categories]
"ammonia cracker" = "Ammonia Cracking"
"Fischer-Tropsch" = "Fischer-Tropsch"
"H2 Electrolysis" = "Electrolysis"
"H2 Fuel Cell" = "Electricity"
"H2 OCGT" = "Electricity"
"H2 for industry" = "Industry"
"H2 turbine" = "Electricity"
"Haber-Bosch" = "Haber-Bosch"
"SMR" = "SMR"
"SMR CC" = "SMR"
"Sabatier" = "Sabatier"
"electrobiofuels" = "Synth. Fuels"
"land transport fuel cell" = "Transport"
"methanolisation" = "Methanolisation"
"solid biomass to hydrogen" = "H2 from Solid Biomass"
"Net Export" = "Net Export"
"Net Import" = "Net Import"
"Storage In" = "Storage In"
"Storage Out" = "Storage Out"

[view.capacity.ac_storage]
name = "Power Storage Volumes"
unit = "TWh"
file_name = "capacity_ac_storage_{location}_{year}"
cutoff = 0.00001  # 1 MWh
legend_order = []

[view.capacity.ac_storage.checks]

[view.capacity.ac_storage.export]
plotly = true
csv = false
excel = false

[view.capacity.ac_storage.categories]
"" = ""
