[global]
#subdirectory = "OS/tests"

[view.capacity.heat]
name = "District Heat Production Capacities"
unit = "GW"
file_name = "capacity_heat_{location}"
cutoff = 0.0001
legend_order = [
    "Storage Out",
    "Solar Thermal",
    "Fischer-Tropsch",
    "Biomass CHP",
    "Oil CHP",
    "Waste CHP",
    "Electrolysis",
    "Haber-Bosch",
    "Direct Air Capture",
    "CHP",
    "Heat Vent",
    "Methanolisation",
    "Fuel Cell",
    "Resistive Heater",
    "Gas Boiler",
    "Gas CHP",
    "Coal CHP",
    "Heat Pump",
    "Storage In",
]

[view.capacity.heat.checks]
all_categories_mapped = true
no_superfluous_categories = true
yearly_balances_almost_zero = false
legend_entry_order = true

[view.capacity.heat.export]
plotly = true
csv = true
excel = true

[view.capacity.heat.categories]
"DAC" = "Direct Air Capture"
"Fischer-Tropsch" = "Fischer-Tropsch"
"Haber-Bosch" = "Haber-Bosch"
"H2 Electrolysis" = "Electrolysis"
"H2 Fuel Cell" = "Fuel Cell"
"methanolisation" = "Methanolisation"
"urban central air heat pump" = "Heat Pump"
"urban central CHP" = "CHP"
"urban central coal CHP" = "Coal CHP"
"urban central gas CHP" = "Gas CHP"
"urban central oil CHP" = "Oil CHP"
"waste CHP" = "Waste CHP"
"waste CHP CC" = "Waste CHP"
"urban central gas boiler" = "Gas Boiler"
"urban central heat vent" = "Heat Vent"
"urban central lignite CHP" = "Coal CHP"
"urban central resistive heater" = "Resistive Heater"
"urban central solar thermal" = "Solar Thermal"
"urban central solid biomass CHP" = "Biomass CHP"
"urban central water tanks charger" = "Storage In"
"urban central water tanks discharger" = "Storage Out"

[view.balance.hydrogen]
name = "Hydrogen Energy Balance"
unit = "TWh"
file_name = "nodal_hydrogen_balance_{location}"
cutoff = 0.001
legend_order = [
    # production ordered from zero to outside
    "Electrolysis",
    "SMR",
    "H2 from Solid Biomass",
    "Ammonia Cracking",
    "Storage",
    "Import Domestic",
    "Import European",
    # demand ordered from zero to outside:
    "Methanolisation",
    "Industry",
    "Transport",
    "Electricity",
    "Haber-Bosch",
    "Fischer-Tropsch",
    "Sabatier",
    "Synth. Fuels",
    "Export Domestic",
    "Export European",
]

[view.balance.hydrogen.checks]
all_categories_mapped = true
no_superfluous_categories = true
legend_entry_order = true
yearly_balances_almost_zero = true

[view.balance.hydrogen.export]
plotly = true
csv = true
excel = true

[view.balance.hydrogen.categories]
"ammonia cracker" = "Ammonia Cracking"
"Export European" = "Export European"
"Export Domestic" = "Export Domestic"
"Fischer-Tropsch" = "Fischer-Tropsch"
"H2 Electrolysis" = "Electrolysis"
"H2 Fuel Cell" = "Electricity"
"H2 OCGT" = "Electricity"
"H2 for industry" = "Industry"
"H2 turbine" = "Electricity"
"H2 Store" = "Storage"
"Haber-Bosch" = "Haber-Bosch"
"Import European" = "Import European"
"Import Domestic" = "Import Domestic"
"SMR" = "SMR"
"SMR CC" = "SMR"
"Sabatier" = "Sabatier"
"electrobiofuels" = "Synth. Fuels"
"land transport fuel cell" = "Transport"
"methanolisation" = "Methanolisation"
"solid biomass to hydrogen" = "H2 from Solid Biomass"

[view.timeseries.hydrogen]
name = "Hydrogen Production and Demand"
unit = "MWh"
file_name = "timeseries_hydrogen_{location}_{year}"
cutoff = 0.001
legend_order = [
    "Synth. Fuels",
    "Storage Out",
    "Ammonia Cracking",
    "Sabatier",
    "Net Import",
    "Haber-Bosch",
    "Electricity",
    "Electrolysis",
    "Methanolisation",
    "Net Export",
    "H2 from Solid Biomass",
    "SMR",
    "Transport",
    "Storage In",
    "Industry",
    "Fischer-Tropsch",
]

[view.timeseries.hydrogen.checks]
all_categories_mapped = true
no_superfluous_categories = true
legend_entry_order = true
yearly_balances_almost_zero = false
timestep_balances_almost_zero = true

[view.timeseries.hydrogen.export]
plotly = true
csv = false
excel = false

[view.timeseries.hydrogen.categories]
"ammonia cracker" = "Ammonia Cracking"
"Fischer-Tropsch" = "Fischer-Tropsch"
"H2 Electrolysis" = "Electrolysis"
"H2 Fuel Cell" = "Electricity"
"H2 OCGT" = "Electricity"
"H2 for industry" = "Industry"
"H2 turbine" = "Electricity"
"Haber-Bosch" = "Haber-Bosch"
"SMR" = "SMR"
"SMR CC" = "SMR"
"Sabatier" = "Sabatier"
"electrobiofuels" = "Synth. Fuels"
"land transport fuel cell" = "Transport"
"methanolisation" = "Methanolisation"
"solid biomass to hydrogen" = "H2 from Solid Biomass"
"Net Export" = "Net Export"
"Net Import" = "Net Import"
"Storage In" = "Storage In"
"Storage Out" = "Storage Out"
