name: CI Testrun

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  schedule:
  - cron: "0 5 * * 0"
  workflow_dispatch:

# Cancel any in-progress runs when a new run is triggered
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-pixi:
    name: PyPSA-AT CI Test Run
    runs-on: ubuntu-latest
    #container:
    #  image: ghcr.io/prefix-dev/pixi:latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        # Remove tools that are not needed
        tool-cache: false
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true

    - name: Install Pixi
      uses: prefix-dev/setup-pixi@v0.8.1
      with:
        pixi-version: latest

    - name: Setup cache keys
      run: |
        echo "WEEK=$(date +'%Y%U')" >> $GITHUB_ENV

    - name: Cache data and cutouts
      uses: actions/cache@v4
      with:
        path: |
          data
          cutouts
        key: data-cutouts-${{ env.WEEK }}

    - name: Build scenarios
      run: pixi run snakemake -call build_scenarios

    - name: Run AT10 test config
      run: pixi run snakemake -call all --configfile=config/test/config.at10.yaml

    - name: Run unit tests
      run: pixi run pytest test -m "unit or integration"

    - name: Upload artifacts
      if: always()
      uses: actions/upload-artifact@v5
      with:
        name: test-results-pixi
        path: |
          logs
          .snakemake/log
          results
        retention-days: 3
